main: ${mainClass}
name: ${name}
version: ${version}
author: ${author}
description: ${description}
api-version: 1.16
softdepend: [Votifier]

commands:
  vote:
    description: vote
  votes:
    description: votes
  votetop:
    description: vote top
  fakevote:
    description: fakevote
  votereload:
    description: reload
  setvotes:
    description: set votes