main: ${mainClass}
name: ${name}
version: ${version}
author: ${author}
description: ${description}
api-version: 1.14
softdepend: [ NuVotifier, Votifier, Vault, PlaceholderAPI, Multiverse-Core ]

commands:
  vote:
    description: vote
    permission: customvoting.vote
  votes:
    description: votes
    permission: customvoting.vote
  votetop:
    description: vote top
    permission: customvoting.votetop
  fakevote:
    description: fakevote
    permission: customvoting.fakevote
  setvotes:
    description: set votes
    permission: customvoting.setvotes
  clearperiodvotes:
    description: clear period votes
    permission: customvoting.period
  createtop:
    description: create top stand
    permission: customvoting.createtop
  deletetop:
    description: delete top stand
    permission: customvoting.deletetop
  voteparty:
    description: vote party
    permission: customvoting.voteparty
  votereload:
    description: reload
    permission: customvoting.reload
  votesettings:
    description: vote settings
    permission: customvoting.settings
    aliases: [ vsettings ]

permissions:
  customvoting.*:
    default: op
    children:
      customvoting.vote: true
      customvoting.votes.*: true
      customvoting.period: true
      customvoting.votetop: true
      customvoting.createtop: true
      customvoting.deletetop: true
      customvoting.fakevote: true
      customvoting.voteparty: true
      customvoting.reload: true
      customvoting.settings: true
  customvoting.vote:
    default: true
  customvoting.votes.*:
    default: op
    children:
      customvoting.votes: true
      customvoting.votes.others: true
      customvoting.votes.set: true
  customvoting.votes:
    default: true
  customvoting.votes.others:
    default: op
  customvoting.votes.set:
    default: op
  customvoting.period:
    default: op
  customvoting.createtop:
    default: op
  customvoting.deletetop:
    default: op
  customvoting.votetop:
    default: true
  customvoting.votetop.signs:
    default: op
  customvoting.fakevote:
    default: op
  customvoting.voteparty:
    default: op
  customvoting.reload:
    default: op
  customvoting.settings:
    default: op
  customvoting.extra:
    default: false