# CustomVoting by sd_master92

monthly_reset: false
sound_effects: true
firework: true
vote_party: true
vote_party_type: 0
vote_party_countdown: 30
votes_required_for_vote_party: 10
vote_reward_money: 100
vote_reward_xp: 3
lucky_vote: true
lucky_vote_chance: 50
forbidden_commands:
  - fakevote
  - op
  - stop
  - restart
  - reload
ingame_updates: true
use_database: false
database:
  host: localhost
  port: 3306
  database: customvoting
  user: root
  password: root