# Custom Voting by sd_master92

monthly_reset: false
sound_effects: true
firework: true
vote_party: true
vote_party_type: 0
vote_party_countdown: 30
votes_required_for_vote_party: 10
vote_reward_money: 100
vote_reward_xp: 3